### ISSUE TITLE
Getting problem with local_position setpoint

### ISSUE THREAD

**Issue by gajena** [weiweikong/auto_landing#2]
Hey, @weiweikong  I am working on a quite similar problem.
But I am getting no response from the autopilot.
* I am publishing aruco position data to `/mavros/vision_pose/pose`
* Giving position setpoint on `mavros/setpoint_position/local`
* But facing the problem like autopilot not generating the corresponding setpoint on handheld testing.
What do you think that what is the problem??
My publisher rate is 30 hz, and local position working for `yaw`heading and `z setpoint`.

**Comment by weiweikong** [comment]
Hi @gajena , the position estimation algorithms works not quite well during my testing, due to the poor accuracy localization from aruco tag.  You could test the local position data while manually moving slowly the drone and monitor the results from QGroudcontrol or publisher to see whether the ouput is correct.

**Comment by gajena** [comment]
Okay, I will do this thing.
Then how did you perform your aruco landing task??
